[versions]
gradle = "8.5.1"
jetpack_compose_compiler = "1.5.14"
kotlin = "2.0.0"
coroutine = "1.8.1"
accompanist = "0.34.0"
lifecycle = "2.8.4"
arch_core_testing = "2.2.0"
appcompat = "1.7.0"
activity_ktx = "1.9.1"
fragment_ktx = "1.8.2"
preference = "1.2.1"
browser = "1.8.0"
recyclerview = "1.3.2"
constraintlayout = "2.1.4"
material = "1.12.0"
retrofit = "2.11.0"
firebase_bom = "33.1.2"
jacoco = "0.8.7"
glide = "4.16.0"
work = "2.9.0"
dagger_hilt = "2.51.1"
sql_delight = "1.5.5"
sqlite = "2.4.0"
timber = "5.0.1"
flipper = "0.260.0"
junit = "4.13.2"
baselineprofile = "1.3.3"

[plugins]
kotlin-gradle = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "gradle" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
android-application = { id = "com.android.application", version.ref = "gradle" }

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "junit:junit", version.ref = "junit" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

compose_bom = { module = "androidx.compose:compose-bom", version = "2024.06.00" }
accompanist = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
firebase-ads = { module = "com.google.firebase:firebase-ads", version = "23.2.0" }

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity_ktx" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment_ktx" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
sqlite = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version = "1.1.0" }
annotation = { module = "androidx.annotation:annotation", version = "1.8.1" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch_core_testing" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

material = { module = "com.google.android.material:material", version.ref = "material" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }

flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
flipper-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
soloader = { module = "com.facebook.soloader:soloader", version = "0.11.0" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger_hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger_hilt" }
dagger-hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger_hilt" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

sqldelight = { module = "com.squareup.sqldelight:android-driver", version.ref = "sql_delight" }
sqldelight-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sql_delight" }
sqldelight-gradle = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sql_delight" }

jsoup = { module = "org.jsoup:jsoup", version = "1.18.1" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

materialshowcaseview = { module = "com.github.deano2390:MaterialShowcaseView", version = "1.3.7" }

firebase_bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom" }

androidx_test_core = { module = "androidx.test:core", version = "1.6.1" }
androidx_test_runner = { module = "androidx.test:runner", version = "1.6.2" }
androidx_test_rules = { module = "androidx.test:rules", version = "1.6.1" }
androidx_test = { module = "androidx.test.ext:junit", version = "1.2.1" }
espresso = { module = "androidx.test.espresso:espresso-core", version = "3.6.1" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.3.0" }
macrobenchmark = { module = "androidx.benchmark:benchmark-macro-junit4", version = "1.2.4" }
spoon = { module = "com.squareup.spoon:spoon-client", version = "1.7.1" }
assertj = { module = "org.assertj:assertj-core", version = "3.26.3" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version = "1.3.1" }

[bundles]
lifecycle = ["lifecycle-viewmodel", "lifecycle-livedata"]